apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Rental Service
  description: Application which allows agents to complete the complete rental process 
  tags: 
    - javascript
    - java 
    - python
  links:
    - title: api-docs
      url: http://localhost:8081/swagger-ui/index.html
    # - title: Documentation
    #   url: https://backstage.io/docs
    # - title: Storybook
    #   url: https://backstage.io/storybook
    # - title: Discord Chat
    #   url: https://discord.com/invite/EBHEGzX
  annotations:
    # github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: http://localhost:8081/swagger-ui/index.html
    # lighthouse.com/website-url: https://backstage.io
spec:
  type: website
  owner: rental-nam
  lifecycle: experimental
  consumesApi: TeamsNotifier
